#!/bin/sh

# Set defaults
export MYSQL_PORT=${MYSQL_PORT:-3306}
export MYSQL_OPTS=${MYSQL_OPTS:-}
export MYSQL_BULK_INSERT_BUFFER_SIZE=${MYSQL_BULK_INSERT_BUFFER_SIZE:-16M}
export MYSQL_CONCURRENT_INSERT=${MYSQL_CONCURRENT_INSERT:-2}
export MYSQL_CONNECT_TIMEOUT=${MYSQL_CONNECT_TIMEOUT:-5}
export MYSQL_KEY_BUFFER_SIZE=${MYSQL_KEY_BUFFER_SIZE:-384M}
export MYSQL_MAX_ALLOWED_PACKET=${MYSQL_MAX_ALLOWED_PACKET:-32M}
export MYSQL_MAX_HEAP_TABLE_SIZE=${MYSQL_MAX_HEAP_TABLE_SIZE:-32M}
export MYSQL_MYISAM_SORT_BUFFER_SIZE=${MYSQL_MYISAM_SORT_BUFFER_SIZE:-64M}
export MYSQL_READ_BUFFER_SIZE=${MYSQL_READ_BUFFER_SIZE:-2M}
export MYSQL_READ_RND_BUFFER_SIZE=${MYSQL_READ_RND_BUFFER_SIZE:-8M}
export MYSQL_SORT_BUFFER_SIZE=${MYSQL_SORT_BUFFER_SIZE:-2M}
export MYSQL_TABLE_OPEN_CACHE=${MYSQL_TABLE_OPEN_CACHE:-512}
export MYSQL_THREAD_CACHE_SIZE=${MYSQL_THREAD_CACHE_SIZE:-8}
export MYSQL_THREAD_STACK=${MYSQL_THREAD_STACK:-400K}
export MYSQL_TMP_TABLE_SIZE=${MYSQL_TMP_TABLE_SIZE:-32M}
export MYSQL_WAIT_TIMEOUT=${MYSQL_WAIT_TIMEOUT:-600}
export MYSQL_QUERY_CACHE_LIMIT=${MYSQL_QUERY_CACHE_LIMIT:-1M}
export MYSQL_QUERY_CACHE_SIZE=${MYSQL_QUERY_CACHE_SIZE:-64M}
export MYSQL_INNODB_BUFFER_POOL_SIZE=${MYSQL_INNODB_BUFFER_POOL_SIZE:-384M}
export MYSQL_INNODB_DATA_FILE_PATH=${MYSQL_INNODB_DATA_FILE_PATH:-ibdata1:256M;ibdata2:128M:autoextend}
export MYSQL_INNODB_LOG_BUFFER_SIZE=${MYSQL_INNODB_LOG_BUFFER_SIZE:-8M}
export MYSQL_INNODB_LOG_FILE_SIZE=${MYSQL_INNODB_LOG_FILE_SIZE:-100M}
export MYSQL_INNODB_FILE_PER_TABLE=${MYSQL_INNODB_FILE_PER_TABLE:-1}
export MYSQL_INNODB_OPEN_FILES=${MYSQL_INNODB_OPEN_FILES:-256}
export MYSQL_INNODB_IO_CAPACITY=${MYSQL_INNODB_IO_CAPACITY:-512}
export MYSQL_INNODB_THREAD_CONCURRENCY=${MYSQL_INNODB_THREAD_CONCURRENCY:-8}
export MYSQL_INNODB_LOCK_WAIT_TIMEOUT=${MYSQL_INNODB_LOCK_WAIT_TIMEOUT:-120}
export MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT=${MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT:-0}
export MYSQL_INNODB_FLUSH_METHOD=${MYSQL_INNODB_FLUSH_METHOD:-O_DIRECT}

# Render configuration files
/usr/local/bin/confd -onetime -backend env
