[template]
# Conifguration template
src     = "client.cnf.tmpl"
# Rendered configuration file location
dest    = "/etc/mysql/percona-server.conf.d/client.cnf"

# File ownership
owner   = "ash"
group   = "ash"
mode    = "0644"
